apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: guestbook-app
  namespace: guestbook
  labels:
    app: guestbook-app
  annotations:
    apps.open-cluster-management.io/git-path: guestbook-app/guestbook
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: guestbook/guestbook-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: guestbook-pr
