---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  namespace: guestbook
  name: redis-slave-app
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - redis-slave-app
